sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
before_install:
  - pip install poetry
install:
  - poetry install -v
  - pip install tox-travis
script: 
  - pytest tests/
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"
