site_name: pyparam
theme:
    name: 'yeti'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
nav:
    - 'Introduction': 'index.md'
