site_name: pyparam
theme:
    name: 'material'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
nav:
    - 'Introduction': 'index.md'
    - 'From command line arguments': 'fromCommandline.md'
    - 'Shell completions': 'shellCompletions.md'
    - 'Help page': 'helpPage.md'
    - 'From dict': 'fromDict.md'
    - 'From file': 'fromFile.md'
    - 'Subcommands': 'commands.md'
    - 'Use the values': 'useTheValues.md'
    - 'Change log': 'changeLog.md'