site_name: pyparam
theme:
    name: 'material'
    # font:
    #   text: 'Ubuntu'
    #   code: 'Ubuntu Mono'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi
extra_css:
    - style.css
nav:
    - 'Home': 'index.md'
    - 'Defining parameters': 'TypesOfParams.md'
    - 'Commands': 'commands.md'
    - 'Parsing from command line': 'fromCommandline.md'
    - 'Loading from dict/config file': 'fromDict.md'
    - 'Help page': 'helpPage.md'
    - 'Using the parsed values': 'useTheValues.md'
    - 'API': mkapi/api/pyparam
    - 'Change log': 'changeLog.md'
