[tool.poetry]
name = "pyparam"
version = "0.0.1"
description = "Powerful parameter processing."
authors = ["pwwang <pwwang@pwwang.com>"]
license = "MIT"
readme = "README.md"
packages = [
	{include = "param.py"}
]

[tool.poetry.dependencies]
python = "^3.3"
colorama = "*"
python-simpleconf = "^0.1.3"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
